### ISSUE TITLE
Exclude phrases that are in quotes?

### ISSUE THREAD

**Issue by squeek502** [plorry/VegAssist#11]
I've noticed most of the false positives are tweets by people using a matching phrase within a quote ([this tweet for example](https://twitter.com/BrittniKristine/status/659595657376731140)).

It would take a bit of work, but we could check that the matching phrase is not surrounded by double quotes. Unsure if it's worth it or not.

**Comment by squeek502** [comment]
Seems like this might be worthwhile.

Some more examples:
- https://twitter.com/eveysaranghae/status/661336091539189760
- https://twitter.com/bdmicky/status/661253312180838400
- https://twitter.com/uyentngo/status/660998841202704390

@plorry, thoughts?

**Comment by plorry** [comment]
@squeek502 Good call.
Maybe our methods to test for filter matches could return the exact expression matched, using a RegExp.exec(). Then we have another method, `tweetIsQuotedText` (or something) that gets passed in the tweet & the matching expression, and checks if it's got a quote mark before and after it, anywhere in the tweet.
Does that sound efficient? Other thoughts on how to do it?
Getting the expression match returned would also be useful for logging, so we could keep a log of exactly which matches were most common.

**Comment by squeek502** [comment]
Yeah, that's how I was thinking it could be done as well. If we have the match, we could use a regex check like this:

``` javascript
new RegExp('"[^"]*' + matchingPhrase + '[^"*]"', "i")
```

It would have false positives, but they should be rare. For example, it would match a format like this:

```
"i like to quote" i want to go vegan "i really like quotes"
```
