### ISSUE TITLE
Matches log a little over-eagerly

### ISSUE THREAD

**Issue by plorry** [plorry/VegAssist#16]
![image](https://cloud.githubusercontent.com/assets/811275/11039459/c7183020-86d5-11e5-80d8-fda001e71ad7.png)

This is a sample of the `matches` log from a recent tweet: https://twitter.com/OPMKZA/status/663743992899727361

@squeek502

**Comment by squeek502** [comment]
Fair enough. Note that that's the output of `RegExp.exec` (because we have so many matching groups in our RegExp expressions). I'll make the format more concise when logging.

**Comment by plorry** [comment]
@squeek502 Ah, I get how that output works. Thanks for taking the issue! And for the logging in general!
