### ISSUE TITLE
Spanish phrases by /u/wannabered22

### ISSUE THREAD

**Issue by squeek502** [plorry/VegAssist#20]
Just wanted to make sure these didn't get lost in the shuffle.

From [this comment](https://www.reddit.com/r/vegan/comments/3sfhtv/approximately_every_45_minutes_someone_tweets/cwxf3sr):
- Quisiera ser vegana
- Quiero ser vegana
- Quisiera hacerme vegana
- Quiero hacerme vegana
- Ya no quiero comer animales (i don't want to eat animals anymore)

I'm not totally sure how the twitter API works. Will tracking `vegan` catch `vegana` too? That's something we need to confirm/deny.

The last phrase would require tracking `animales`, which we might not want to do?

**Comment by plorry** [comment]
Hmm, yeah, if _I_ were designing the Twitter API, I'd probably have it filter exact matches only. Can we have two streams running simultaneously? Sounds like some experimenting is needed...

**Comment by squeek502** [comment]
If that's true, then half of the Dutch filters aren't currently functional either. I noticed that @joriskcf has some unmerged changes on their fork related to this: https://github.com/joriskcf/VegAssist/commit/e9cdf4758b9f9de7ce433d80174be528833aed99

**Comment by squeek502** [comment]
API docs about `statuses/filter` -> `track`: https://dev.twitter.com/streaming/overview/request-parameters#track

**Comment by plorry** [comment]
Heh, just finished reading that too. That's great - one stream tracking the term in multiple languages.

**Comment by squeek502** [comment]
So we do need to track each translation of vegan, even if vegan is a substring of the translation.

From the docs:

`Twitter` **will not match** `TwitterTracker`

**Comment by plorry** [comment]
Yeah, a comma-separated list should work - which is good, because the word is probably dramatically different in some languages. I think it's "vegetalien" in French, for example, which wouldn't partial match "vegan" anyway.

**Comment by squeek502** [comment]
Sometimes I feel like a vegetalien.

**Comment by plorry** [comment]
:seedling: :alien:

**Comment by squeek502** [comment]
By the way, looks like @joriskcf was correct: [Twit will automatically convert arrays to a comma-separated string](https://github.com/ttezel/twit/blob/master/lib/twitter.js#L96-L97). So https://github.com/joriskcf/VegAssist/commit/e9cdf4758b9f9de7ce433d80174be528833aed99 is probably what we want to do.

**Comment by moshpirit** [comment]
It doesn't seem to work with Spanish anymore ([screenshot](https://i.imgur.com/iPl2zbz.png)), may I ask why not? is there any way I can help you with that? I'm no developer but I'm Spanish and the `spanish.js` code seems simple

**Comment by moshpirit** [comment]
BTW wouldn't be better to have separated bots for each language? I mean, that way I could only follow the English and the Spanish bots, but ignore the Portuguese, Italian, etc ones
