### ISSUE TITLE
Portuguese (maybe other languages) can get a false positive match on a negative sentiment

### ISSUE THREAD

**Issue by plorry** [plorry/VegAssist#25]
I'm not familiar with the structure of Portuguese, but it seems that a negating statement can still match our filters. The translation for "I want to go vegan" and " I don't want to go vegan" both match.

Eg: https://twitter.com/_farytopia/status/666450937188323330

Is there a way we can turn them into regex phrases that fail when there's a specific word at the start or end? Would the negative lookahead work for this purpose? http://stackoverflow.com/questions/1240275/how-to-negate-specific-word-in-regex/1240365#1240365

(My RegEx is weak)

@filp - any thoughts?

**Comment by squeek502** [comment]
Checking the start would need a negative lookbehind, and lookbehinds don't exist in Javascript's regex implementation.

One way around that would be to match the RegEx as normal, and then split the tweet into 3 parts--before the matching phrase, the matching phrase, and after the matching phrase--and then run regex's on the before and after that would exclude the tweet if they matched. This is basically the same thing that the quote detector does currently (which I did try using regex for at one point and ran into the same lookbehind issue).

If we wanted to do that, it might be best to add a third supported filter type that is a function, and then just do all the logic in that. Or perhaps an array of [regex|string, function] where the regex/string is applied as normal but the matching phrase and full text is passed to the function to see if it should be excluded.
