### ISSUE TITLE
gh-pages branch can be orphaned

### ISSUE THREAD

**Issue by squeek502** [plorry/VegAssist#27]
Just wanted to see if removing all the bot code stuff from the gh-pages branch could be done, so I tried it out. Here's the result: https://github.com/squeek502/VegAssist/commits/gh-pages

What I did (note that cloning a fresh copy is useful to avoid already having a local gh-pages branch and/or having extraneous files in the directory):

```
git clone https://github.com/plorry/VegAssist.git
cd VegAssist
git checkout --orphan gh-pages
git rm -rf .
git commit --allow-empty -m "Empty commit of orphaned gh-pages branch"
git cherry-pick 82db4dfce2f98165e389b54bc7dffc0d4753182a^..eba92d570dec01f6fd4bb8b84eaf1c6b2e8e5ced
```

Let me know if it'd be alright for me to force push this branch to the main repository's gh-pages branch.

**Comment by plorry** [comment]
@squeek502 Sorry for letting this sit! For sure feel free to push this.

**Comment by squeek502** [comment]
Done. Note that because the two branches no longer share history, it's easier to check out two separate instances of the repository (one for each branch) than to switch back and forth between branches when you want to make changes to the `gh-pages` branch.
