### ISSUE TITLE
Add a hashtag filter for asking questions

### ISSUE THREAD

**Issue by joriskcf** [plorry/VegAssist#29]
What do you think about adding a `#vegquestions` or `#vegassist` filter that people could use to ask questions about going vegan? That way people who find out about the bot could share their questions with all the bot's followers, without having to match one of the current filters.

**Comment by joriskcf** [comment]
One problem I see that might happen is people using the hashtag incorrectly (like when answering questions) which could get spammy.

**Comment by squeek502** [comment]
I think the intention behind this might be worth addressing. Right now, tweets _to_ @VegAssist aren't visible to followers of the bot. I think @plorry has manually retweeted a few ([example](https://twitter.com/garethgra/status/682956330706022400)), but it might be nice to automate that in some way.

As far as I can tell, though, these sort of tweets are quite rare, so maybe manual retweets can cover it.

**Comment by joriskcf** [comment]
I didn't really consider @mentions because I though that would include people replying to retweets, but now I think about it that could easily be avoided by excluding tweets with multiple mentions.

> As far as I can tell, though, these sort of tweets are quite rare, so maybe manual retweets can cover it.

They might become less rare if we tell people about it (when replying to retweets). If people have questions a few days after their initial tweet, they probably won't send out another tweet that would match one of the filters, and they probably wouldn't feel comfortable contacting one of the people that replied initially.

**Comment by squeek502** [comment]
Right, there have been a few instances of that I've seen and the second tweet sometimes gets ignored. Would it be too much to retweet all tweets that only mention @VegAssist (and perhaps only when it's at the start or end of the tweet)? Seems potentially abusable, but I'm not sure how else to go about it.

EDIT: Here's an example of a tweet to VegAssist that got no action: https://twitter.com/Dadto_Carson33/status/671113287745085440

**Comment by joriskcf** [comment]
I don't really expect any big problems, but it might be a good idea to keep a close eye on it for a while if we try it. One thing we could do to mitigate (flood) abuse is limit the amount of mentions retweeted per X time.

**Comment by ghost** [comment]
I like this idea too. It provides people with a way to follow-up after getting a re-tweet from @VegAssist. 

Just as an added note. is it possible to add to the bot's description on the right-side a FAQ or links about going vegan? this may help people who go to the bot's page to know more after getting a re-tweet.

**Comment by plorry** [comment]
I'll consider this closed with @Shaderboy's latest push.
Can revisit if we want to do it by hashtag.
