### ISSUE TITLE
Delayed RTing might help the freak-out factor

### ISSUE THREAD

**Issue by plorry** [plorry/VegAssist#33]
Some people get a little spooked that they get RT'd right away. Also, we have some eager followers, who reply within seconds sometimes - this has evoked a few responses asking person to "chill" or for the RT'd person to delete their original tweet. Maybe delaying RTs by 5 minutes would make it feel a little more "organic" - give the tweeter a bit of time to breathe/reflect before getting response.

**Comment by ghost** [comment]
I like this idea. I think if people are getting almost instant replies on their tweets it can feel overwhelming. 5 minutes seems like a reasonable delay.

**Comment by squeek502** [comment]
Good idea :+1:

**Comment by hallomatt** [comment]
Great idea! I saw this yesterday:

> Harley || 9 ‏@JackFalaFox 17. Feb.
> 
> @JackFalaFox I LITTERALY TWEETED THIS A SECOND AGO WHY DOES IT ALREADY HABE AN RT LIKE AS SOON AS I TWEETED IT THERE WAS AN RT ON KF

IMO, a 2 minute delay would be perfect, since it's really nice to get a quick reply.
Anything faster than 30 seconds is a bit spooky though :)

**Comment by plorry** [comment]
#36 should solve this - tested in the wild, and seems to behave as expected.
