### ISSUE TITLE
Wiki page for vegan advice

### ISSUE THREAD

**Issue by ghost** [plorry/VegAssist#47]
I would like to start off a Wiki page for vegan advice; for example, it would be great to know what are the good vegan cheeses in the US as I don't live there.

This is something the wider Reddit community can contribute too.

What do people think?

**Comment by squeek502** [comment]
Sounds like a good idea. Maybe it'd be worth doing on the /r/vegan wiki?

https://www.reddit.com/r/vegan/wiki/index

Looks like /u/IceRollMenu2 has created a similar page for clothing: https://www.reddit.com/r/vegan/wiki/clothes-and-apparels
