### ISSUE TITLE
Might be worth trying to stem recidivism as well

### ISSUE THREAD

**Issue by bradbeattie** [plorry/VegAssist#48]
Some matching of the form "hard time staying vegan" or some such. Came across this tweet that I'd think VegAssist's mandate might cover: https://twitter.com/badlandskies/status/732730352222019586

**Comment by plorry** [comment]
@bradbeattie this is a good idea. If you wanted to make a PR with some matching RegEx's for this, I'd approve it! If you haven't necessarily got the time, I can add them myself shortly too! Cheers!
